# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fd20ec35fec64b2caa4a07c366cbc4f41117224cbdee2cb25c0a3bbad730e274b5a3d6d2a2b434872b17ab1816748faf5af49372724b0ea926984f31b08bef0

test:
  secret_key_base: f9d09a93457014a9a906868f026a71d70678710bb1a8bd0e89ce2fecf670956e2e18f84ef5e645dcf805651db59af4f0582a15866a7f9afefe05e273a0635dbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
